language: cpp

os:
  - linux
  - osx

compiler:
    - gcc
    - clang

matrix:
    exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

before_install:
  - git clone https://github.com/physycom/sysconfig.git
  - export WORKSPACE=$(pwd)/..

install:
  - mkdir build && cd build

script:
  - cmake ..
  - cmake --build .
