language: cpp

os:
  - linux
  - osx

compiler:
    - gcc
    - clang

matrix:
    exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

before_install:
  - git clone https://github.com/physycom/sysconfig.git
  - export SYSCONFIG_PATH=$(pwd)/sysconfig

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget --no-check-certificate http://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz   ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xzf cmake-3.8.0-Linux-x86_64.tar.gz                                                  ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PWD/cmake-3.8.0-Linux-x86_64/bin:$PATH                                       ;fi
  - mkdir build && cd build

script:
  - cmake .. "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=${SYSCONFIG_PATH}/cmake/physycom_toolchain.cmake"
  - cmake --build .
