language: cpp

os:
  - linux
  - osx

compiler:
    - gcc
    - clang

matrix:
    exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

before_install:
  - git clone https://github.com/physycom/sysconfig.git
  - export SYSCONFIG_PATH=$(pwd)/sysconfig

install:
  - mkdir build && cd build

script:
  - cmake .. "-DCMAKE_TOOLCHAIN_FILE=${SYSCONFIG_PATH}/cmake/supertoolchain.cmake"
  - cmake --build .
